version: "3.3"

services:
  database:
    container_name: flask_data_colector
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=af1235512355
      - POSTGRES_USER=joao
    ports:
      - 5434:5432